site_name: Simplified Doc
docs_dir: docs/
site_author: Gosoft
copyright: Copyright &copy; Gosoft Thailand Co.,Ldt
site_url: https://simplifieddata.github.io/SimplifiedDoc/
repo_name: SimplifiedData/SimplifiedDoc
repo_url: https://github.com/SimplifiedData/SimplifiedDoc.git

theme:
  name: material
  font:
    text: ember
  palette:
    # - primary: lime
    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - toc.integrate
    