name: ci 
on:
  push:
    branches:
      - main
env:
    PYTHON_VERSION: 3.x

permissions:
  contents: read
jobs:
  deploy:
    name: Deploy docs
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - name: Checkout main
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
        with:
          fetch-depth: 0

      - name: Configure Git Credentials
        run: |
          git config user.name 101Krit
          git config user.email 122605335+101Krit@users.noreply.github.com
          
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
            python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install mkdocs-material \
            mkdocs-include-markdown-plugin \
            mkdocs-awesome-pages-plugin

      - run: mkdocs gh-deploy --force